name: app_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy=1.21.5
  - scikit-learn=1.2.0
  - joblib=1.2.0
  - streamlit=1.9.0
  - pip:
      - wandb